CREATE TYPE perk AS ENUM ('READERSHIP','MENTOR','VIP','STAFF');

CREATE TABLE Person
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR        NOT NULL CHECK (length(name) > 2 AND length(name) < 30),
    age          INT CHECK (age > 0),
    email        VARCHAR UNIQUE NOT NULL,
    address      VARCHAR        NOT NULL,
    phone_number VARCHAR(11),
    perk         perk
);
