CREATE TYPE perk AS ENUM ('READERSHIP','MENTOR','VIP','STAFF');

CREATE TABLE Person
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR        NOT NULL CHECK (length(name) > 2 AND length(name) < 30),
    age          INT CHECK (age > 0),
    email        VARCHAR UNIQUE NOT NULL,
    address      VARCHAR        NOT NULL,
    phone_number VARCHAR(11),
    perk         perk
);

INSERT INTO person (name, age, email, address, phone_number, perk)
VALUES ('Тихомиров Илья Алексеевич', 19, '76myxomor76@gmail.com', 'Россия, СПб, Красносельский', '89214489228',
        'STAFF'),
       ('Рэдли Брайан', 20, 'kolmogorov.un@gmail.com', 'Россия, Ленинградская, Всеволожский', '89219205851', 'VIP'),
       ('Иванов Иван', 51, 'tor@yandex.ru', 'Украина, Чернигов, Новозаводской', '89219217278', 'READERSHIP'),
       ('Алексеев Алексей Алексеевич', 32, 'redshift@mail.ru', 'Беларусь, Минск, Малиновка', '89214759632', 'MENTOR'),
       ('Петров Пётр Петрович', 16, 'position@gmail.com', 'Россия, Москва, Химки', '89214415684', 'VIP'),
       ('Фёдоров Мирон', 39, 'world@gmail.com', 'Украина, Киев, Подольский', '89215556248', 'READERSHIP'),
       ('Тарцай Эрвин Эдмундович', 13, 'tarsway@mail.ru', 'Венгрия, Будапешт, Чепель', '89214563211', 'READERSHIP'),
       ('Лехвеслайхо Дональд', 63, 'lis@gmail.com', 'США, Алабама, Бирмингем', '89211015601', 'READERSHIP'),
       ('Дональд Кнут', 52, 'knuth@gmail.com', 'США, Кентукки, Луисвилл', '89214652130', 'MENTOR'),
       ('Джон Вирт', 54, 'virtualBox@mail.com', 'Мексика, Дуранго, Дуранго', '89214756523', 'VIP')
;
