CREATE TABLE child
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR        NOT NULL,
    surname VARCHAR        NOT NULL,
    age     INT CHECK (age > 0),
    email   VARCHAR UNIQUE NOT NULL,
    CHECK (length(name) > 2 AND length(name) < 30)
);